
SELECT 'CREATE TABLE TAVERNS (' as ' '
UNION ALL
SELECT
concat (column_name,' ', data_type,(CASE WHEN data_type = 'varchar' THEN '(50)' ELSE '' END),',') AS ' '
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tavern_info'
UNION ALL
SELECT ');';


SELECT 'CREATE TABLE FK_RELATIONSHIPS (' as ' '
UNION ALL
SELECT
concat (table_name,' ', column_name,' ',  )  AS ' '
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
UNION ALL
SELECT ');';





SELECT 'CREATE TABLE TAVERNS_REF (' as ' '
UNION ALL
SELECT
concat (INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME,' ', data_type,(CASE WHEN data_type = 'varchar' THEN '(50)' ELSE '' END),' ', CONSTRAINT_TYPE,' ','REFERENCES',' ', UNIQUE_CONSTRAINT_NAME,',') AS ' '
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE JOIN INFORMATION_SCHEMA.COLUMNS ON CONCAT(INFORMATION_SCHEMA.COLUMNS.TABLE_NAME, INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME) = CONCAT(INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_NAME, INFORMATION_SCHEMA.KEY_COLUMN_USAGE.COLUMN_NAME)
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS ON INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS ON INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME = INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
UNION ALL
SELECT ');';


SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS



SELECT 'CREATE TABLE TAVERNS (' as ' '
UNION ALL
SELECT
concat (column_name,' ', data_type,(CASE WHEN data_type = 'varchar' THEN '(50)' ELSE '' END),',') AS ' '
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tavern_info'
UNION ALL
SELECT ');';